[package]
name = "keyboard"
version = "0.1.0"
edition = "2021"
description = "Keyboard input handler"

[dependencies]
pc-keyboard = "0.5.1"
printk = { path = "../../../kernel/printk/" }

[dependencies.crossbeam-queue]
version = "0.2.1"
default-features = false
features = ["alloc"]

[dependencies.futures-util]
version = "0.3.4"
default-features = false
features = ["alloc"]
