[package]
name = "invic"
version = "0.1.0"
edition = "2021"
description = "NVIC irqchip driver"

[dependencies]
cortex-m = "0.7.5"
cortex-m-rt = "0.7.1"
hio = { path = "../../platform/arm/hio/" }
novuskinc = { path = "../../../include/novusk/" }

[features]
debug = []
