[package]
name = "setup"
version = "0.1.0"
edition = "2021"
description = "Setup before kernel_init and setup before kernel_main"
publish = false

[dependencies]
novuskinc = { path = "../../include/novusk/" }
printk = { path = "../printk/" }
