[package]
name = "i8259"
version = "0.1.0"
edition = "2021"
description = "A driver for the PIC8259 IRQ chip"
publish = false

[dependencies]
asminc = { path = "../../../include/asm/" }
novuskinc = { path = "../../../include/novusk/" }
pic8259 = "0.10.2"
spin = "0.9.3"
