[package]
name = "vgag"
version = "0.1.0"
edition = "2021"
description = "Vga graphics driver"
license = "MIT"
publish = false

[dependencies]
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
novuskinc = "0.1.1"
spin = "0.9.2"
vga = "0.2.7"
