[package]
name = "stellariskern"
version = "0.1.0"
edition = "2021"
description = "Stellaris device specific kernel"

[[bin]]
name = "a32dImage"
path = "src/main.rs"

[dependencies]
arm = { path = "../../../../arch/arm/", features = ["stellaris6965"] }
asminc = { path = "../../../../include/asm/" }
cortex-m = "0.7.4"
cortex-m-rt = "0.7.1"
cortex-m-semihosting = "0.5.0"
nmallocator = { path = "../../../../mm/nmallocator/" }
stellaris = { path = "../" }
