[package]
name = "arm"
version = "0.1.0"
edition = "2021"
description = "ARM (32) kernel"

[dependencies]
asminc = { path = "../../include/asm/" }
dif = { path = "../../include/dif/" }
nmallocator = { path = "../../mm/nmallocator/" }
novuskinc = { path = "../../include/novusk/" }
printk = { path = "../../kernel/printk/" }
setup = { path = "../../kernel/setup/" }

[features]
cortex_a = []
cortex_m = []
rpi2b = ["cortex_a"]
stellaris6965 = ["cortex_m"]
stm32f407 = ["cortex_m"]
