[package]
name = "printk"
version = "0.1.0"
edition = "2021"
description = "Kernel printing function and macro"
license = "MIT"
publish = false

[dependencies]
console = { path = "console/" }
novuskinc = { git = "https://github.com/new-kernel/novuskinc/" }
