[package]
name = "irq"
version = "0.1.0"
edition = "2021"
description = "Main kernel IRQ handler"

[lib]
name = "irq"
crate-type = ["staticlib"]

[dependencies]
asminc = { path = "../../include/asm/" }
novuskinc = { path = "../../include/novusk/" }
printk = { path = "../printk/" }
