[package]
name = "x86_64"
version = "0.1.0"
edition = "2021"
description = "x86_64 support for Novusk"

[lib]
name = "x86_64_kernel_lib"
edition = "2021"
crate-type = ["staticlib"]
path = "src/lib.rs"

[[bin]]
name = "x86_64_kernel_bin"
edition = "2021"
path = "src/main.rs"

[dependencies]
asminc = { path = "../../include/asm/" }
i8259 = { path = "../../drivers/irqchip/i8259/" }
kinfo = { path = "../../kernel/kinfo/" }
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
libcolor = { path = "../../lib/libcolor/" }
memory = { path = "../../mm/memory/" }
nmallocator = { path = "../../mm/nmallocator/", features = ["wee_allocator"] }
novuskinc = { path = "../../include/novusk/", features = ["library"] }
printk = { path = "../../kernel/printk/" }
ps2_keyboard = { path = "../../drivers/input/keyboard/ps2_keyboard/" }
raw-cpuid = "10.2.0"
setup = { path = "../../kernel/setup/" }
spin = "0.9.2"
vgag = { path = "../../drivers/gpu/vgag/", features = ["no_panic"] }
volatile = "0.3.0"
x86_64 = "0.14.9"

[features]
pic8259_irqchip = []
