[package]
name = "pc_keyboard"
version = "0.1.0"
edition = "2021"
description = "A driver for to handle PC Keyboard input"

[dependencies]
asminc = { path = "../../../../include/asm/" }
novuskinc = { path = "../../../../include/novusk/" }
