[package]
name = "bcm"
version = "0.1.0"
edition = "2021"
description = "An SOC driver for Broadcom CPUs"

[dependencies]
novuskinc = { path = "../../../include/novusk/" }
soc = { path = "../" }
tock-registers = "0.7.0"

[features]
soc_selected = []
bcm2837 = ["soc_selected"]
