[package]
name = "stellaris"
version = "0.1.0"
edition = "2021"
description = "A driver for Stellaris devices"

[dependencies]
dif = { path = "../../../include/dif/" }
hio = { path = "../arm/hio/" }
novuskinc = { path = "../../../include/novusk/" }
tm4c123x = "0.9.0"
tm4c123x-hal = "0.10.2"

[build-dependencies]
difi = { path = "../../../tools/build/difi/" }
