[package]
name = "stellaris"
version = "0.1.0"
edition = "2021"
description = "A driver for Stellaris devices"

[dependencies]
asminc = { path = "../../../include/asm/" }
cortex-m = "0.7.5"
cortex-m-rt = "0.7.1"
dif = { git = "https://github.com/new-kernel/dif" }
hio = { path = "../arm/hio/" }
invic = { path = "../../irqchip/invic/" }
novuskinc = { path = "../../../include/novusk/" }
tm4c123x = "0.9.0"
tm4c123x-hal = "0.10.2"

[build-dependencies]
difi = { path = "../../../tools/build/difi/" }

[features]
s6965 = []
s811 = []
