[package]
name = "rpi"
version = "0.1.0"
edition = "2021"
description = "Setup for RaspberryPi devices"

[lib]
path = "src/lib.rs"
crate-type = ["staticlib"]

[dependencies]
asminc = { path = "../../../include/asm/" }
bcm = { path = "../../soc/bcm/" }
novuskinc = { path = "../../../include/novusk/" }
nmallocator = { path = "../../../mm/nmallocator/", features = ["wee_allocator"] }
printk = { path = "../../../kernel/printk/" }
soc = { path = "../../soc/" }
tock-registers = "0.7.0"

[build-dependencies]
difi = { path = "../../../tools/build/difi/" }

[features]
dev_selected = []
rpi3 = ["dev_selected", "bcm/bcm2837"]
