[package]
name = "lba"
version = "0.1.0"
edition = "2021"
description = "Logical Block Addressing (LBA) driver for x86_64"

[dependencies]
asminc = { path = "../../../include/asm/" }
novuskinc = { path = "../../../include/novusk/" }
printk = { path = "../../../kernel/printk/" }
