[package]
name = "stmkern"
version = "0.1.0"
edition = "2021"
description = "STM device specific kernel"

[dependencies]
cortex-m = "0.7.4"
cortex-m-rt = "0.7.1"

[[bin]]
name = "a32dImage"
path = "src/main.rs"

[features]
stm32f407 = []
