[package]
name = "console"
version = "0.1.0"
edition = "2021"
description = "This is the main kernel console driver"
license = "MIT"
publish = false

[dependencies]
dif = "0.1.1"
novuskinc = { git = "https://github.com/new-kernel/novuskinc" }
