[package]
name = "aarch64"
version = "0.1.0"
edition = "2021"
description = "Aarch64/arm64 kernel support"

[lib]
name = "aarch64_kernel_lib"
path = "src/lib.rs"
crate-type = ["staticlib"]
edition = "2021"

[[bin]]
name = "aarch64_kernel_bin"
path = "src/main.rs"
edition = "2021"

[dependencies]
asminc = { path = "../../include/asm/" }
# bcm = { path = "../../drivers/soc/bcm/" }
cortex-a = "7.4.0"
dif = { git = "https://github.com/new-kernel/dif/" }
kinfo = { path = "../../kernel/kinfo/" }
nmallocator = { path = "../../mm/nmallocator/", features = ["wee_allocator"] }
novusk_syscalls = "0.2.1"
novuskinc = { path = "../../include/novusk/", features = ["library"] }
printk = { path = "../../kernel/printk/" }
tock-registers = "0.7.0"
r0 = "1.0.0"
setup = { path = "../../kernel/setup/" }
soc = { path = "../../drivers/firmware/soc/" }
spin = "0.9.2"

[features]
default = []
rpi3b = ["bcm_soc"]
rpi4b = ["bcm_soc"]
bcm_soc = []
qemu_virt = []
